/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nhsys.ui;

/**
 *
 * @author VU
 */
public class VB_Loading extends javax.swing.JFrame implements Runnable {

    public static int mahd;

    /**
     * Creates new form Load
     */
    public VB_Loading() {
        initComponents();
        Thread t1 = new Thread(this);
        t1.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLoading = new javax.swing.JLabel();
        lblPhanTram = new javax.swing.JLabel();
        Loading = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LoadingForm");
        setMinimumSize(new java.awt.Dimension(840, 380));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblLoading.setBackground(new java.awt.Color(51, 51, 255));
        lblLoading.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblLoading.setForeground(new java.awt.Color(51, 51, 255));
        lblLoading.setText("Loading..");

        lblPhanTram.setBackground(new java.awt.Color(51, 51, 255));
        lblPhanTram.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPhanTram.setForeground(new java.awt.Color(51, 51, 255));
        lblPhanTram.setText("0%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(lblLoading, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPhanTram))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhanTram)
                    .addComponent(lblLoading)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 230, -1));

        Loading.setBackground(new java.awt.Color(204, 204, 204));
        Loading.setForeground(new java.awt.Color(51, 51, 255));
        Loading.setPreferredSize(new java.awt.Dimension(146, 15));
        getContentPane().add(Loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 840, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhsys/icon/logo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 290, 260));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhsys/icon/Wellcome.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VB_Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VB_Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VB_Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VB_Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VB_Loading().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Loading;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLoading;
    private javax.swing.JLabel lblPhanTram;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        VB_Login login = new VB_Login();
        try {

            for (int i = 0; i <= 100; i++) {
                Thread.sleep(30);
                Loading.setValue(i);
                lblPhanTram.setText(i + "%");
                if (i == 10) {
                    lblLoading.setText("Turning on model...");
                }
                if (i == 20) {
                    lblLoading.setText("Loading model...");
                }
                if (i == 50) {
                    lblLoading.setText("Connecting to database...");
                }
                if (i == 70) {
                    lblLoading.setText("Connection Suscesful...");
                }
                if (i == 80) {
                    lblLoading.setText("Lauching Application...");
                }

            }

        } catch (Exception ex) {

        }

        login.setVisible(true);
        dispose();
    }
}
