/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nhsys.panel.quanly;

import com.nhsys.dao.HangHoaDAO;
import com.nhsys.entity.HangHoa;
import com.nhsys.utils.MsgBox;
import com.nhsys.utils.XDate;
import com.nhsys.utils.XNumber;
import com.nhsys.utils.mouseEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hai Tran
 */
public class QL_HangHoa extends javax.swing.JPanel {

    javax.swing.Timer t;

    //Biến
    /**
     * Creates new form HangHoaPanel
     */
    public QL_HangHoa() {
        initComponents();
        init();
    }

    //end
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        txtMaHH = new javax.swing.JTextField();
        txtTenHH = new javax.swing.JTextField();
        txtDonVi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        btnLamMoi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cldNgayNhap = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        txtSoLuong = new javax.swing.JFormattedTextField();
        txtChiPhi = new javax.swing.JFormattedTextField();
        txtTongChiPhi = new javax.swing.JFormattedTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        btnXuat = new javax.swing.JButton();
        txtSearchTenHH = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDSHangHoa = new javax.swing.JTable();

        setBackground(new java.awt.Color(248, 242, 242));
        setMinimumSize(new java.awt.Dimension(1109, 593));

        tabs.setBackground(new java.awt.Color(255, 255, 255));
        tabs.setForeground(new java.awt.Color(255, 153, 51));
        tabs.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tabs.setMinimumSize(new java.awt.Dimension(110, 110));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        txtMaHH.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtTenHH.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtDonVi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("THÔNG TIN CƠ BẢN");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhsys/icon/coding.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhsys/icon/box.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhsys/icon/unit.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhsys/icon/amount.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhsys/icon/cash.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhsys/icon/calendarB24.png"))); // NOI18N

        btnLamMoi.setBackground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhsys/icon/refreshO.png"))); // NOI18N
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Mã hàng hóa");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("Tên hàng hóa");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("Đơn vị tính");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("Số lượng kiểm kê");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("Chi phí");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("Ngày nhập");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setText("Tổng chi phí");

        cldNgayNhap.setDateFormatString("dd-MM-yyyy");
        cldNgayNhap.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cldNgayNhap.setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        btnThem.setBackground(new java.awt.Color(51, 204, 0));
        btnThem.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel1.add(btnThem);

        btnXoa.setBackground(new java.awt.Color(255, 87, 87));
        btnXoa.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("XÓA");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel1.add(btnXoa);

        btnSua.setBackground(new java.awt.Color(255, 153, 51));
        btnSua.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("SỬA");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSua);

        txtSoLuong.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtSoLuong.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtSoLuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSoLuongMouseClicked(evt);
            }
        });
        txtSoLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSoLuongKeyReleased(evt);
            }
        });

        txtChiPhi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.0"))));
        txtChiPhi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtChiPhi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtChiPhiMouseClicked(evt);
            }
        });
        txtChiPhi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtChiPhiKeyReleased(evt);
            }
        });

        txtTongChiPhi.setEditable(false);
        txtTongChiPhi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.0"))));
        txtTongChiPhi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel17))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel13)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMaHH, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                                    .addComponent(txtTenHH, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                                    .addComponent(cldNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDonVi, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                                    .addComponent(txtSoLuong)
                                    .addComponent(txtChiPhi)
                                    .addComponent(txtTongChiPhi)))
                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(240, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtChiPhi, txtDonVi, txtMaHH, txtSoLuong, txtTenHH, txtTongChiPhi});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtTenHH)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(txtMaHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cldNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(txtChiPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTongChiPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel9))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cldNgayNhap, txtChiPhi, txtDonVi, txtMaHH, txtSoLuong, txtTenHH, txtTongChiPhi});

        tabs.addTab("Cập nhật", jPanel4);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(900, 723));

        btnXuat.setBackground(new java.awt.Color(255, 153, 51));
        btnXuat.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnXuat.setForeground(new java.awt.Color(255, 255, 255));
        btnXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhsys/icon/excel.png"))); // NOI18N
        btnXuat.setText("XUẤT EXCEL");
        btnXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatActionPerformed(evt);
            }
        });

        txtSearchTenHH.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtSearchTenHH.setText("Tên hàng hóa");
        txtSearchTenHH.setBorder(null);
        txtSearchTenHH.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchTenHHFocusLost(evt);
            }
        });
        txtSearchTenHH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchTenHHMouseClicked(evt);
            }
        });
        txtSearchTenHH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchTenHHActionPerformed(evt);
            }
        });
        txtSearchTenHH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchTenHHKeyPressed(evt);
            }
        });

        tblDSHangHoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Hàng Hóa", "Tên Hàng Hóa", "Ngày Nhập", "Đơn Vị", "Số Lượng", "Chi Phí", "Tổng Chi Phí"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDSHangHoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSHangHoaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDSHangHoa);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXuat)
                    .addComponent(txtSearchTenHH, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(846, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearchTenHH, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabs.addTab("Danh sách Hàng hóa", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnXuatActionPerformed

    private void txtSearchTenHHFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchTenHHFocusLost
        new mouseEvent().clear_text_exit(txtSearchTenHH, "Tên hàng hóa");
    }//GEN-LAST:event_txtSearchTenHHFocusLost

    private void txtSearchTenHHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchTenHHMouseClicked
        new mouseEvent().clear_text_click(txtSearchTenHH, "Tên hàng hóa");
    }//GEN-LAST:event_txtSearchTenHHMouseClicked

    private void tblDSHangHoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSHangHoaMouseClicked
        if (evt.getClickCount() == 2) {
            this.row = tblDSHangHoa.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tblDSHangHoaMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (!checkVal()) {
            return;
        }
        this.insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        clearForm();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void txtSoLuongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoLuongKeyReleased
        // TODO add your handling code here:
        updateTongChiPhi();
    }//GEN-LAST:event_txtSoLuongKeyReleased

    private void txtChiPhiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChiPhiKeyReleased
        // TODO add your handling code here:
        updateTongChiPhi();
    }//GEN-LAST:event_txtChiPhiKeyReleased

    private void txtSoLuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSoLuongMouseClicked
        // TODO add your handling code here:
        txtSoLuong.selectAll();
    }//GEN-LAST:event_txtSoLuongMouseClicked

    private void txtChiPhiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtChiPhiMouseClicked
        // TODO add your handling code here:
        txtChiPhi.selectAll();
    }//GEN-LAST:event_txtChiPhiMouseClicked

    private void txtSearchTenHHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchTenHHKeyPressed
        fillTableByName();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchTenHHKeyPressed

    private void txtSearchTenHHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchTenHHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchTenHHActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuat;
    private com.toedter.calendar.JDateChooser cldNgayNhap;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblDSHangHoa;
    private javax.swing.JFormattedTextField txtChiPhi;
    private javax.swing.JTextField txtDonVi;
    private javax.swing.JTextField txtMaHH;
    private javax.swing.JTextField txtSearchTenHH;
    private javax.swing.JFormattedTextField txtSoLuong;
    private javax.swing.JTextField txtTenHH;
    private javax.swing.JFormattedTextField txtTongChiPhi;
    // End of variables declaration//GEN-END:variables
    HangHoaDAO dao = new HangHoaDAO();
    int row = -1;

    String patternNumber = "#,##0.00";

    void init() {
        tblDSHangHoa.setDefaultEditor(Object.class, null);
        this.fillTable(); // đổ dữ liệu nhân viên vào bảng
        this.updateStatus(); // cập nhật trạng thái form
    }

    void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblDSHangHoa.getModel();
        model.setRowCount(0);
        try {
            List<HangHoa> list = dao.selectAll();
            for (HangHoa hh : list) {
                Object[] row = {
                    hh.getMaHangHoa(),
                    hh.getTenHangHoa(),
                    XDate.formatDate1(hh.getNgayNhap()),
                    hh.getDonVi(),
                    hh.getSoLuong(),
                    hh.getChiPhi(),
                    hh.getTongChiPhi()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
            e.printStackTrace();
        }
    }

    void updateTongChiPhi() {

//        if (txtSoLuong.getText().isEmpty() || txtSoLuong.getText().equalsIgnoreCase("")) {
//            SL = 0;
//            txtTongChiPhi.setText("");
//        } else {
//            SL = Double.parseDouble(txtSoLuong.getText());
//        }
//        if (txtChiPhi.getText().isEmpty() || txtChiPhi.getText().equalsIgnoreCase("")) {
//            CP = 0;
//            txtTongChiPhi.setText("");
//        } else {
//            CP = Double.parseDouble(txtChiPhi.getText());
//        }
//        TCP = SL * CP;
//        txtTongChiPhi.setText(String.valueOf(TCP));
        if (txtSoLuong.getText().length() == 0 || txtSoLuong.getText() == null) {
            txtSoLuong.setText("0");
        }
        if (txtChiPhi.getText().length() == 0 || txtChiPhi.getText() == null) {
            txtChiPhi.setText("0");
        }

        double soLuong = 0;
        double chiPhi = 0;
        double tongChiPhi = 0;

        // Bắt lỗi định dạng số
        try {
            chiPhi = Double.parseDouble(txtChiPhi.getText());
            if (chiPhi < 0) {
                MsgBox.alert(this, "Chi phí phải là số không âm!");
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Chi phí không đúng định dạng");
            txtChiPhi.setText("0");
        }
        try {
            soLuong = Double.parseDouble(txtSoLuong.getText());
            if (soLuong < 0) {
                MsgBox.alert(this, "Số lượng phải là số không âm!");
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Số lượng không đúng định dạng!");
            txtSoLuong.setText("0");
        }

        tongChiPhi = chiPhi * soLuong;
        txtTongChiPhi.setText(XNumber.convertToString(tongChiPhi, patternNumber));
    }

    void fillTableByName() {
        String Chuoitimkiem = txtSearchTenHH.getText();
        DefaultTableModel model = (DefaultTableModel) tblDSHangHoa.getModel();
        model.setRowCount(0);
        try {
            List<HangHoa> list = dao.SearchByNameHH(Chuoitimkiem);
            for (HangHoa hh : list) {
                Object[] row = {
                    hh.getMaHangHoa(),
                    hh.getTenHangHoa(),
                    XDate.formatDate1(hh.getNgayNhap()),
                    hh.getDonVi(),
                    hh.getSoLuong(),
                    hh.getChiPhi(),
                    hh.getTongChiPhi()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    void updateStatus() {
        boolean edit = (this.row >= 0);
        // Trạng thái form
        txtMaHH.setEditable(!edit);
        btnThem.setEnabled(!edit);
        btnSua.setEnabled(edit);
        btnXoa.setEnabled(edit);
        btnLamMoi.setEnabled(edit);
        // Trạng thái điều hướng
    }

    boolean checkVal() {
        Date ngayHT = XDate.toDate(java.time.LocalDate.now().toString(), "yyyy-MM-dd");
        Date ngayNhap = cldNgayNhap.getDate();
        if (txtMaHH.getText().isEmpty() || txtMaHH.getText().equalsIgnoreCase("")) {
            MsgBox.alert(this, "Bạn chưa nhập mã hàng hóa!");
            return false;
        }
        if (txtTenHH.getText().isEmpty() || txtTenHH.getText().equalsIgnoreCase("")) {
            MsgBox.alert(this, "Bạn chưa nhập tên hàng hóa!");
            return false;
        }
        if (ngayNhap.before(ngayHT)) {
            MsgBox.alert(this, "Ngày nhập hàng không được nhỏ hơn ngày hiện tại!");
            return false;
        }
        if (txtDonVi.getText().isEmpty() || txtDonVi.getText().equalsIgnoreCase("")) {
            MsgBox.alert(this, "Bạn chưa nhập đơn vị hàng hóa");
            return false;
        }
        if (txtSoLuong.getText().isEmpty() || txtSoLuong.getText().equalsIgnoreCase("")) {
            MsgBox.alert(this, "Bạn chưa nhập Số Lượng");
            return false;
        }
        if (txtChiPhi.getText().isEmpty() || txtChiPhi.getText().equalsIgnoreCase("")) {
            MsgBox.alert(this, "Bạn chưa nhập chi phí");
            return false;
        }
        return true;
    }

    void insert() {
        HangHoa hh = this.getForm();
        try {
            dao.insert(hh); // thêm mới
            this.fillTable(); // đỗ lại bảng
            this.clearForm(); // xóa trắng form
            MsgBox.alert(this, "Thêm mới thành công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Thêm mới thất bại!");
        }
    }

    void update() {
        HangHoa hh = this.getForm();
        try {
            dao.update(hh); // cập nhật
            this.fillTable(); // đổ lại bảng
            MsgBox.alert(this, "Cập nhật thành công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Cập nhật thất bại!");
        }
    }

    void delete() {
        String mahh = txtMaHH.getText();
        try {
            dao.delete(mahh);
            this.fillTable();
            this.clearForm();
            MsgBox.alert(this, "Xóa thành công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Xóa thất bại!");
        }
    }

    void edit() {
        String mahh = (String) tblDSHangHoa.getValueAt(this.row, 0);
        HangHoa hh = dao.selectById(mahh);
        this.setForm(hh);
        this.updateStatus();
        tabs.setSelectedIndex(0);
    }

    void clearForm() {
        HangHoa hh = new HangHoa();
        this.setForm(hh);
        this.row = -1;
        this.updateStatus();
        txtMaHH.requestFocus();
        txtSoLuong.setText("0");
        txtChiPhi.setText("0");
    }

    void setForm(HangHoa hh) {
        txtMaHH.setText(hh.getMaHangHoa());
        txtTenHH.setText(hh.getTenHangHoa());
//        cldNgayNhap.setDate(hh.getNgayNhap());
        txtDonVi.setText(hh.getDonVi());
        txtSoLuong.setText(XNumber.convertToString(hh.getSoLuong(), patternNumber));
        txtChiPhi.setText(XNumber.convertToString(hh.getChiPhi(), patternNumber).replaceAll(",", ""));
        txtTongChiPhi.setText(XNumber.convertToString(hh.getTongChiPhi(), patternNumber));
    }

    HangHoa getForm() {
        HangHoa hh = new HangHoa();
        hh.setMaHangHoa(txtMaHH.getText());
        hh.setTenHangHoa(txtTenHH.getText());
        SimpleDateFormat dt1 = new SimpleDateFormat("yyyy-MM-dd");
        hh.setNgayNhap(dt1.format(cldNgayNhap.getDate()));
        hh.setDonVi(txtDonVi.getText());
        hh.setSoLuong(XNumber.convertToDouble(txtSoLuong.getText(), patternNumber));
        hh.setChiPhi(XNumber.convertToDouble(txtChiPhi.getText(), patternNumber));
        hh.setTongChiPhi(XNumber.convertToDouble(txtTongChiPhi.getText(), patternNumber));
        return hh;
    }

    Double TCP() {
        double SL = 0;
        double CP = 0;
        double TCP = 0;
        if (txtSoLuong.getText().isEmpty()) {
            SL = 0;
        } else {
            SL = Double.parseDouble(txtSoLuong.getText());
        }
        if (txtChiPhi.getText().isEmpty()) {
            CP = 0;
        } else {
            CP = Double.parseDouble(txtChiPhi.getText());
        }
        TCP = SL * CP;
        txtTongChiPhi.setText(String.valueOf(TCP));
        return TCP;
    }

}
