/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nhsys.panel.quanly;

import java.awt.Color;

/**
 *
 * @author Hai Tran
 */
public class QL_MenuQL extends javax.swing.JPanel {

    /**
     * Creates new form QL_MenuCN
     */
    public QL_MenuQL() {
        initComponents();
        jpnCenterQL.updateUI();
        reloadPanelMenu(1);
    }
    QL_ThucDon QL_ThucDon;
    QL_NhanVienJPN QL_NhanVienJPN;
    QL_HangHoa QL_HangHoa;
    QL_DoanhThuThang QL_DoanhThuThang;
 
    public void reloadPanelMenu(int i) {
        jpnCenterQL.removeAll();
        switch (i) {
            case 1:
                QL_NhanVienJPN = new QL_NhanVienJPN();
                jpnCenterQL.add(QL_NhanVienJPN);
                lblHeader.setText("Quản Lý Nhân Viên");
                break;
            case 2:
                QL_ThucDon = new QL_ThucDon();
                jpnCenterQL.add(QL_ThucDon);
                lblHeader.setText("Quản Lý Thực Đơn");
                break;
            case 3:
                QL_HangHoa = new QL_HangHoa();
                jpnCenterQL.add(QL_HangHoa);
                lblHeader.setText("Quản Lý Hàng Hóa");
                break;
            case 4:
                QL_DoanhThuThang = new QL_DoanhThuThang();
                jpnCenterQL.add(QL_DoanhThuThang);
                lblHeader.setText("Doanh Thu Tháng");
                break;

        }
        jpnCenterQL.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpnNhanVienCN = new javax.swing.JPanel();
        lblNhanVienCN = new javax.swing.JLabel();
        jpnDoanhThuCN = new javax.swing.JPanel();
        lblDoanhThuCN = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jpnThucDonCN = new javax.swing.JPanel();
        lblThucDonCN = new javax.swing.JLabel();
        jpnHangHoaCN = new javax.swing.JPanel();
        lblHangHoaCN = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        jpnCenterQL = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 153, 51));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jpnNhanVienCN.setBackground(new java.awt.Color(204, 204, 204));
        jpnNhanVienCN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnNhanVienCNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpnNhanVienCNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpnNhanVienCNMouseExited(evt);
            }
        });

        lblNhanVienCN.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblNhanVienCN.setForeground(new java.awt.Color(255, 255, 255));
        lblNhanVienCN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNhanVienCN.setText("NHÂN VIÊN");
        lblNhanVienCN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNhanVienCNMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnNhanVienCNLayout = new javax.swing.GroupLayout(jpnNhanVienCN);
        jpnNhanVienCN.setLayout(jpnNhanVienCNLayout);
        jpnNhanVienCNLayout.setHorizontalGroup(
            jpnNhanVienCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNhanVienCNLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(lblNhanVienCN, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnNhanVienCNLayout.setVerticalGroup(
            jpnNhanVienCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnNhanVienCNLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(lblNhanVienCN)
                .addGap(22, 22, 22))
        );

        jpnDoanhThuCN.setBackground(new java.awt.Color(204, 204, 204));
        jpnDoanhThuCN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnDoanhThuCNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpnDoanhThuCNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpnDoanhThuCNMouseExited(evt);
            }
        });

        lblDoanhThuCN.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblDoanhThuCN.setForeground(new java.awt.Color(255, 255, 255));
        lblDoanhThuCN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoanhThuCN.setText("DOANH THU");
        lblDoanhThuCN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDoanhThuCNMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnDoanhThuCNLayout = new javax.swing.GroupLayout(jpnDoanhThuCN);
        jpnDoanhThuCN.setLayout(jpnDoanhThuCNLayout);
        jpnDoanhThuCNLayout.setHorizontalGroup(
            jpnDoanhThuCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDoanhThuCN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnDoanhThuCNLayout.setVerticalGroup(
            jpnDoanhThuCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnDoanhThuCNLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(lblDoanhThuCN)
                .addGap(22, 22, 22))
        );

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhsys/icon/logo2ne.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jpnThucDonCN.setBackground(new java.awt.Color(204, 204, 204));
        jpnThucDonCN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnThucDonCNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpnThucDonCNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpnThucDonCNMouseExited(evt);
            }
        });

        lblThucDonCN.setBackground(new java.awt.Color(204, 204, 204));
        lblThucDonCN.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblThucDonCN.setForeground(new java.awt.Color(255, 255, 255));
        lblThucDonCN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThucDonCN.setText("THỰC ĐƠN");
        lblThucDonCN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThucDonCNMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnThucDonCNLayout = new javax.swing.GroupLayout(jpnThucDonCN);
        jpnThucDonCN.setLayout(jpnThucDonCNLayout);
        jpnThucDonCNLayout.setHorizontalGroup(
            jpnThucDonCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblThucDonCN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnThucDonCNLayout.setVerticalGroup(
            jpnThucDonCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThucDonCNLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblThucDonCN)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jpnHangHoaCN.setBackground(new java.awt.Color(204, 204, 204));
        jpnHangHoaCN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnHangHoaCNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpnHangHoaCNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpnHangHoaCNMouseExited(evt);
            }
        });

        lblHangHoaCN.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblHangHoaCN.setForeground(new java.awt.Color(255, 255, 255));
        lblHangHoaCN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHangHoaCN.setText("HÀNG HÓA");
        lblHangHoaCN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHangHoaCNMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnHangHoaCNLayout = new javax.swing.GroupLayout(jpnHangHoaCN);
        jpnHangHoaCN.setLayout(jpnHangHoaCNLayout);
        jpnHangHoaCNLayout.setHorizontalGroup(
            jpnHangHoaCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHangHoaCN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnHangHoaCNLayout.setVerticalGroup(
            jpnHangHoaCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnHangHoaCNLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(lblHangHoaCN)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnThucDonCN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnHangHoaCN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jpnThucDonCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnHangHoaCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnDoanhThuCN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jpnNhanVienCN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jpnNhanVienCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnDoanhThuCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblHeader.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(255, 153, 0));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Quản lý Nhân Viên");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(lblHeader)
                .addContainerGap())
        );

        jpnCenterQL.setBackground(new java.awt.Color(255, 255, 255));
        jpnCenterQL.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnCenterQL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpnCenterQL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblDoanhThuCNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoanhThuCNMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_lblDoanhThuCNMouseClicked

    private void jpnDoanhThuCNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnDoanhThuCNMouseClicked
            reloadPanelMenu(4);
    }//GEN-LAST:event_jpnDoanhThuCNMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void lblNhanVienCNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhanVienCNMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_lblNhanVienCNMouseClicked

    private void lblThucDonCNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThucDonCNMouseClicked

    }//GEN-LAST:event_lblThucDonCNMouseClicked

    private void jpnThucDonCNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnThucDonCNMouseClicked
        // TODO add your handling code here:
        reloadPanelMenu(2);
    }//GEN-LAST:event_jpnThucDonCNMouseClicked

    private void lblHangHoaCNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHangHoaCNMouseClicked

    }//GEN-LAST:event_lblHangHoaCNMouseClicked

    private void jpnHangHoaCNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnHangHoaCNMouseClicked
        // TODO add your handling code here:
        reloadPanelMenu(3);
    }//GEN-LAST:event_jpnHangHoaCNMouseClicked

    private void jpnNhanVienCNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnNhanVienCNMouseEntered
        // TODO add your handling code here:
        if (evt.getSource() == jpnNhanVienCN) {
            jpnNhanVienCN.setBackground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jpnNhanVienCNMouseEntered

    private void jpnNhanVienCNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnNhanVienCNMouseExited
        // TODO add your handling code here:
        if (evt.getSource() == jpnNhanVienCN) {
            jpnNhanVienCN.setBackground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_jpnNhanVienCNMouseExited

    private void jpnDoanhThuCNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnDoanhThuCNMouseEntered
        // TODO add your handling code here:
        if (evt.getSource() == jpnDoanhThuCN) {
            jpnDoanhThuCN.setBackground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jpnDoanhThuCNMouseEntered

    private void jpnDoanhThuCNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnDoanhThuCNMouseExited
        // TODO add your handling code here:
        if (evt.getSource() == jpnDoanhThuCN) {
            jpnDoanhThuCN.setBackground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_jpnDoanhThuCNMouseExited

    private void jpnThucDonCNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnThucDonCNMouseEntered
        // TODO add your handling code here:
        if (evt.getSource() == jpnThucDonCN) {
            jpnThucDonCN.setBackground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jpnThucDonCNMouseEntered

    private void jpnThucDonCNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnThucDonCNMouseExited
        // TODO add your handling code here:
        if (evt.getSource() == jpnThucDonCN) {
            jpnThucDonCN.setBackground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_jpnThucDonCNMouseExited

    private void jpnHangHoaCNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnHangHoaCNMouseEntered
        // TODO add your handling code here:
        if (evt.getSource() == jpnHangHoaCN) {
            jpnHangHoaCN.setBackground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jpnHangHoaCNMouseEntered

    private void jpnHangHoaCNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnHangHoaCNMouseExited
        // TODO add your handling code here:
        if (evt.getSource() == jpnHangHoaCN) {
            jpnHangHoaCN.setBackground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_jpnHangHoaCNMouseExited

    private void jpnNhanVienCNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnNhanVienCNMouseClicked
        // TODO add your handling code here:
        reloadPanelMenu(1);
    }//GEN-LAST:event_jpnNhanVienCNMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jpnCenterQL;
    public static javax.swing.JPanel jpnDoanhThuCN;
    public static javax.swing.JPanel jpnHangHoaCN;
    public static javax.swing.JPanel jpnNhanVienCN;
    public static javax.swing.JPanel jpnThucDonCN;
    public static javax.swing.JLabel lblDoanhThuCN;
    public static javax.swing.JLabel lblHangHoaCN;
    private javax.swing.JLabel lblHeader;
    public static javax.swing.JLabel lblNhanVienCN;
    public static javax.swing.JLabel lblThucDonCN;
    // End of variables declaration//GEN-END:variables

//     public void fillmenuQL(){
//        menu.removeAll();
//        JPanel menuPanel = new NV_MenuMHC(fr);
//        menuPanel.setSize(220, 663);
//        menuPanel.repaint();
//        menuPanel.validate();
//        
//        menu.add(menuPanel);
//        menu.setPreferredSize(new Dimension(220, 663));
//        menu.repaint();
//        menu.validate();
//        
//        ChuyenMangHinhtroller  controller = new ChuyenMangHinhtroller(MHC);
//        controller.setView(jpnSoDoBanQL, lblSoDoBanQL);
//        
//        List<DanhMucBean> listItem =new ArrayList<>();
//        listItem.add(new DanhMucBean("SoDoBan", jpnSoDoBanQL, lblSoDoBanQL));
//        listItem.add(new DanhMucBean("KhoaSo", jpnDoanhThuCN, lblDoanhThuCN));
//        listItem.add(new DanhMucBean("ThanhVien", jpnChamCongCN, lblChamCongCN));      
//        controller.setEvent(listItem);
//    }
}
