/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nhsys.panel.nhanvien;

import com.nhsys.panel.nhanvien.NV_DatBan;
import com.nhsys.panel.nhanvien.NV_DoanhThu;
import com.nhsys.panel.nhanvien.NV_SoDoBan;
import com.nhsys.ui.VB_DoiMK;
import com.nhsys.ui.VB_Login;
import com.nhsys.ui.VB_ManHinhChinh;
import com.nhsys.utils.MsgBox;
import java.awt.Color;
import java.text.ParseException;

/**
 *
 * @author Hai Tran
 */
public class QL_MenuNV extends javax.swing.JPanel {

    /**
     * Creates new form QL_MenuCN
     */
    public QL_MenuNV() {
        initComponents();
        jpnCenterQL_NV.updateUI();
        reloadPanelMenu(1);
    }
    NV_SoDoBan NV_SoDoBan;
    NV_DoanhThu NV_DoanhThu;
    NV_DatBan NV_DatBan;

    public void reloadPanelMenu(int i) {
        jpnCenterQL_NV.removeAll();
        switch (i) {
            case 1:
                NV_SoDoBan = new NV_SoDoBan();
                jpnCenterQL_NV.add(NV_SoDoBan);
                lblHeader.setText("Sơ Đồ Bàn");
                break;
            case 2:
                NV_DoanhThu = new NV_DoanhThu();
                jpnCenterQL_NV.add(NV_DoanhThu);
                lblHeader.setText("Doanh ThuNgày");
                break;
            case 3:
                NV_DatBan = new NV_DatBan();
                jpnCenterQL_NV.add(NV_DatBan);
                lblHeader.setText("Đặt Bàn");
                break;
        }
        jpnCenterQL_NV.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jpnSoDoBanQL = new javax.swing.JPanel();
        lblSoDoBanQL = new javax.swing.JLabel();
        jpnDoanhThuQL = new javax.swing.JPanel();
        lblDoanhThuQL = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jpnDatBanQL = new javax.swing.JPanel();
        lblDatBanQL = new javax.swing.JLabel();
        jpnDoiMK = new javax.swing.JPanel();
        lblDoiMatKhau = new javax.swing.JLabel();
        jpnDangXuat = new javax.swing.JPanel();
        lblDangXuat = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        jpnCenterQL_NV = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 153, 51));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1377, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jpnSoDoBanQL.setBackground(new java.awt.Color(204, 204, 204));
        jpnSoDoBanQL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnSoDoBanQLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpnSoDoBanQLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpnSoDoBanQLMouseExited(evt);
            }
        });

        lblSoDoBanQL.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblSoDoBanQL.setForeground(new java.awt.Color(255, 255, 255));
        lblSoDoBanQL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSoDoBanQL.setText("SƠ ĐỒ BÀN");
        lblSoDoBanQL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSoDoBanQLMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnSoDoBanQLLayout = new javax.swing.GroupLayout(jpnSoDoBanQL);
        jpnSoDoBanQL.setLayout(jpnSoDoBanQLLayout);
        jpnSoDoBanQLLayout.setHorizontalGroup(
            jpnSoDoBanQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSoDoBanQLLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(lblSoDoBanQL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnSoDoBanQLLayout.setVerticalGroup(
            jpnSoDoBanQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnSoDoBanQLLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(lblSoDoBanQL)
                .addGap(21, 21, 21))
        );

        jpnDoanhThuQL.setBackground(new java.awt.Color(204, 204, 204));
        jpnDoanhThuQL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnDoanhThuQLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpnDoanhThuQLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpnDoanhThuQLMouseExited(evt);
            }
        });

        lblDoanhThuQL.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblDoanhThuQL.setForeground(new java.awt.Color(255, 255, 255));
        lblDoanhThuQL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoanhThuQL.setText("DOANH THU");
        lblDoanhThuQL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDoanhThuQLMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnDoanhThuQLLayout = new javax.swing.GroupLayout(jpnDoanhThuQL);
        jpnDoanhThuQL.setLayout(jpnDoanhThuQLLayout);
        jpnDoanhThuQLLayout.setHorizontalGroup(
            jpnDoanhThuQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDoanhThuQLLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(lblDoanhThuQL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnDoanhThuQLLayout.setVerticalGroup(
            jpnDoanhThuQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDoanhThuQLLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblDoanhThuQL)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhsys/icon/logo2ne.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jpnDatBanQL.setBackground(new java.awt.Color(204, 204, 204));
        jpnDatBanQL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnDatBanQLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpnDatBanQLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpnDatBanQLMouseExited(evt);
            }
        });

        lblDatBanQL.setBackground(new java.awt.Color(204, 204, 204));
        lblDatBanQL.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblDatBanQL.setForeground(new java.awt.Color(255, 255, 255));
        lblDatBanQL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDatBanQL.setText("ĐẶT BÀN");
        lblDatBanQL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDatBanQLMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnDatBanQLLayout = new javax.swing.GroupLayout(jpnDatBanQL);
        jpnDatBanQL.setLayout(jpnDatBanQLLayout);
        jpnDatBanQLLayout.setHorizontalGroup(
            jpnDatBanQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnDatBanQLLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDatBanQL)
                .addGap(89, 89, 89))
        );
        jpnDatBanQLLayout.setVerticalGroup(
            jpnDatBanQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDatBanQLLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblDatBanQL)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jpnDoiMK.setBackground(new java.awt.Color(204, 204, 204));
        jpnDoiMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnDoiMKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpnDoiMKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpnDoiMKMouseExited(evt);
            }
        });

        lblDoiMatKhau.setBackground(new java.awt.Color(204, 204, 204));
        lblDoiMatKhau.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblDoiMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        lblDoiMatKhau.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoiMatKhau.setText("  ĐỔI MẬT KHẨU");
        lblDoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDoiMatKhauMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnDoiMKLayout = new javax.swing.GroupLayout(jpnDoiMK);
        jpnDoiMK.setLayout(jpnDoiMKLayout);
        jpnDoiMKLayout.setHorizontalGroup(
            jpnDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnDoiMKLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(lblDoiMatKhau)
                .addGap(53, 53, 53))
        );
        jpnDoiMKLayout.setVerticalGroup(
            jpnDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDoiMKLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblDoiMatKhau)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jpnDangXuat.setBackground(new java.awt.Color(255, 82, 82));
        jpnDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnDangXuatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpnDangXuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpnDangXuatMouseExited(evt);
            }
        });

        lblDangXuat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        lblDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDangXuat.setText("  ĐĂNG XUẤT");
        lblDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnDangXuatLayout = new javax.swing.GroupLayout(jpnDangXuat);
        jpnDangXuat.setLayout(jpnDangXuatLayout);
        jpnDangXuatLayout.setHorizontalGroup(
            jpnDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jpnDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
        );
        jpnDangXuatLayout.setVerticalGroup(
            jpnDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(jpnDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblDangXuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnDoiMK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnDatBanQL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jpnDatBanQL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnDoiMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnDoanhThuQL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jpnSoDoBanQL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jpnSoDoBanQL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnDoanhThuQL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
        });

        lblHeader.setBackground(new java.awt.Color(204, 204, 204));
        lblHeader.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(255, 153, 51));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Sơ Đồ Bàn");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnCenterQL_NV.setBackground(new java.awt.Color(255, 255, 255));
        jpnCenterQL_NV.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnCenterQL_NV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpnCenterQL_NV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblSoDoBanQLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSoDoBanQLMouseClicked
        // TODO add your handling code here:
        //        lblTieuDe.setText("SƠ ĐỒ BÀN");
    }//GEN-LAST:event_lblSoDoBanQLMouseClicked

    private void jpnSoDoBanQLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnSoDoBanQLMouseClicked
        // TODO add your handling code here:
        reloadPanelMenu(1);

    }//GEN-LAST:event_jpnSoDoBanQLMouseClicked

    private void lblDoanhThuQLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoanhThuQLMouseClicked
        // TODO add your handling code here:
        //        lblTieuDe.setText("DANH SÁCH HÓA ĐƠN");
    }//GEN-LAST:event_lblDoanhThuQLMouseClicked

    private void jpnDoanhThuQLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnDoanhThuQLMouseClicked

        // TODO add your handling code here:
        reloadPanelMenu(2);
    }//GEN-LAST:event_jpnDoanhThuQLMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void lblDoiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoiMatKhauMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_lblDoiMatKhauMouseClicked

    private void jpnDoiMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnDoiMKMouseClicked
        try {
            new VB_DoiMK().setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Lỗi:" + e);
        }
    }//GEN-LAST:event_jpnDoiMKMouseClicked

    private void lblDatBanQLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDatBanQLMouseClicked
        //        lblTieuDe.setText("DANH SÁCH ĐẶT BÀN");
    }//GEN-LAST:event_lblDatBanQLMouseClicked

    private void jpnDatBanQLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnDatBanQLMouseClicked
        // TODO add your handling code here:
        reloadPanelMenu(3);
    }//GEN-LAST:event_jpnDatBanQLMouseClicked

    private void lblDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseClicked
        // TODO add your handling code here:
        try {
            if (MsgBox.confirm(this, "Bạn có muốn đăng xuất ?")) {
                new VB_Login().setVisible(true);
                new VB_ManHinhChinh(true).dispose();
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_lblDangXuatMouseClicked

    private void jpnDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnDangXuatMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jpnDangXuatMouseClicked

    private void jpnSoDoBanQLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnSoDoBanQLMouseEntered
        // TODO add your handling code here:
        if (evt.getSource() == jpnSoDoBanQL) {
            jpnSoDoBanQL.setBackground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jpnSoDoBanQLMouseEntered

    private void jpnSoDoBanQLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnSoDoBanQLMouseExited
        // TODO add your handling code here:
        if (evt.getSource() == jpnSoDoBanQL) {
            jpnSoDoBanQL.setBackground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_jpnSoDoBanQLMouseExited

    private void jpnDoanhThuQLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnDoanhThuQLMouseEntered
        // TODO add your handling code here:
        if (evt.getSource() == jpnDoanhThuQL) {
            jpnDoanhThuQL.setBackground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jpnDoanhThuQLMouseEntered

    private void jpnDoanhThuQLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnDoanhThuQLMouseExited
        // TODO add your handling code here:
        if (evt.getSource() == jpnDoanhThuQL) {
            jpnDoanhThuQL.setBackground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_jpnDoanhThuQLMouseExited

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        // TODO add your handling code here:
//          if (evt.getSource() == jPanel2) {
//            jPanel2.setBackground(new Color(153,153,153));
//        }
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jpnDatBanQLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnDatBanQLMouseEntered
        // TODO add your handling code here:
        if (evt.getSource() == jpnDatBanQL) {
            jpnDatBanQL.setBackground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jpnDatBanQLMouseEntered

    private void jpnDatBanQLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnDatBanQLMouseExited
        // TODO add your handling code here:
        if (evt.getSource() == jpnDatBanQL) {
            jpnDatBanQL.setBackground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_jpnDatBanQLMouseExited

    private void jpnDoiMKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnDoiMKMouseEntered
        // TODO add your handling code here:
        if (evt.getSource() == jpnDoiMK) {
            jpnDoiMK.setBackground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jpnDoiMKMouseEntered

    private void jpnDoiMKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnDoiMKMouseExited
        // TODO add your handling code here:
        if (evt.getSource() == jpnDoiMK) {
            jpnDoiMK.setBackground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_jpnDoiMKMouseExited

    private void jpnDangXuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnDangXuatMouseEntered
        // TODO add your handling code here4:
        if (evt.getSource() == jpnDangXuat) {
            jpnDangXuat.setBackground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jpnDangXuatMouseEntered

    private void jpnDangXuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnDangXuatMouseExited
        // TODO add your handling code here:
        if (evt.getSource() == jpnDangXuat) {
            jpnDangXuat.setBackground(new Color(204, 204, 204));
        }

    }//GEN-LAST:event_jpnDangXuatMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jpnCenterQL_NV;
    private javax.swing.JPanel jpnDangXuat;
    public static javax.swing.JPanel jpnDatBanQL;
    public static javax.swing.JPanel jpnDoanhThuQL;
    private javax.swing.JPanel jpnDoiMK;
    public static javax.swing.JPanel jpnSoDoBanQL;
    private javax.swing.JLabel lblDangXuat;
    public static javax.swing.JLabel lblDatBanQL;
    public static javax.swing.JLabel lblDoanhThuQL;
    private javax.swing.JLabel lblDoiMatKhau;
    private javax.swing.JLabel lblHeader;
    public static javax.swing.JLabel lblSoDoBanQL;
    // End of variables declaration//GEN-END:variables

//     public void fillmenuQL(){
//        menu.removeAll();
//        JPanel menuPanel = new NV_MenuMHC(fr);
//        menuPanel.setSize(220, 663);
//        menuPanel.repaint();
//        menuPanel.validate();
//        
//        menu.add(menuPanel);
//        menu.setPreferredSize(new Dimension(220, 663));
//        menu.repaint();
//        menu.validate();
//        
//        ChuyenMangHinhtroller  controller = new ChuyenMangHinhtroller(VB_ManHinhChinh);
//        controller.setView(jpnSoDoBanQL, lblSoDoBanQL);
//        
//        List<DanhMucBean> listItem =new ArrayList<>();
//        listItem.add(new DanhMucBean("SoDoBan", jpnSoDoBanQL, lblSoDoBanQL));
//        listItem.add(new DanhMucBean("KhoaSo", jpnDoanhThuCN, lblDoanhThuCN));
//        listItem.add(new DanhMucBean("ThanhVien", jpnChamCongCN, lblChamCongCN));      
//        controller.setEvent(listItem);
//    }
}
